#!/usr/bin/env sh
confd='/etc/opt/simplex-xftp'
logd='/var/opt/simplex-xftp'

# Avoid a search of PATH
_shd="$(dirname "$0")"
: "${_shd:=/usr/local/bin}"
. "${_shd}/functions.sh"
unset -v _shd

# Check if server has been initialized
if [ ! -f "${confd}/file-server.ini" ]; then
  # If not, determine ip or domain
  set_args_from_env_addr || exit 1

  # Set quota
  append_args_from_env_quota || exit 1

  # Init the certificates and configs
  xftp-server init -l -p /srv/xftp "$@"
fi

# Backup store log just in case
#
# This is the ISO 8601 format without the time zone at the end.
backup_file_iso8601 "${logd}/file-server-store.log"

# Finally, run xftp-sever. Notice that "exec" here is important:
# smp-server replaces our helper script, so that it can catch INT signal
exec xftp-server start +RTS -N -RTS

