#!/usr/bin/env sh
confd='/etc/opt/simplex'
logd='/var/opt/simplex/'

# Avoid a search of PATH
_shd="$(dirname "$0")"
: "${_shd:=/usr/local/bin}"
. "${_shd}/functions.sh"
unset -v _shd

# Check if server has been initialized
if [ ! -f "${confd}/smp-server.ini" ]; then
  # If not, determine ip or domain
  set_args_from_env_addr || exit 1

  # Optionally, set password
  append_args_from_env_pass

  # And init certificates and configs
  smp-server init -y -l "$@"
fi

# Backup store log just in case
#
# This is the ISO 8601 format without the time zone at the end.
backup_file_iso8601 "${logd}/smp-server-store.log"

# Finally, run smp-sever. Notice that "exec" here is important:
# smp-server replaces our helper script, so that it can catch INT signal
exec smp-server start +RTS -N -RTS

