#!/usr/bin/env sh
confd="/etc/opt/simplex"
logd="/var/opt/simplex/"

# Check if server has been initialized
if [ ! -f "$confd/smp-server.ini" ]; then
  # If not, determine ip or domain
  case $addr in
    '') printf "Please specify \$addr environment variable.\n"; exit 1 ;;
    *[a-zA-Z]*) set -- -n $addr ;;
    *) set -- --ip $addr ;;
  esac

  case $pass in
    '') set -- "$@" --no-password ;;
    *) set -- "$@" --password $pass ;;
  esac

  smp-server init -y -l "$@"
fi

# backup store log
_file="${logd}/smp-server-store.log"
if [ -f "${_file}" ]; then
  _backup_extension="$(date --universal '+%04Y-%03m-%02dT%T')"
  cp -v -p "${_file}" "${_file}.${_backup_extension:-date-failed}"
  unset -v _backup_extension
fi
unset -v _file

# Finally, run smp-sever. Notice that "exec" here is important:
# smp-server replaces our helper script, so that it can catch INT signal
exec smp-server start +RTS -N -RTS

